---
title: "pivot_lobsters"
author: "Jewel Uzquiano"
date: "10/11/2021"
output: html_document
---

```{r echo=FALSE}
## attach libraries
library(tidyverse)
library(readxl)
library(here)
library(skimr) #install.packages("skimr")
library(kableExtra) # install.packages("kableExtra")
```

```{r}
## read in data
#lobsters <- read_xlsx(here("data/lobsters.xlsx"), skip = 4)
## read in new data then re-knit
lobsters <- read_xlsx(here("data/lobsters2.xlsx"), skip=4)
## explore data
skimr::skim(lobsters)
```

Let's make a pivot table of the lobsters data

```{r}
lobsters %>% 
  group_by(year) %>% 
  summarize(count_by_year = n())

lobsters %>% 
  summarize(count = n())

lobsters %>% 
  group_by(year)

lobsters %>% 
  group_by(site, year) %>% 
  summarize(count_by_siteyear = n())

## or

siteyear_summary <- lobsters %>% 
  group_by(site, year) %>% 
  summarize(count_by_siteyear = n(),
            mean_size_mm = mean(size_mm, na.rm = TRUE),
            sd_size_mm = sd(size_mm, na.rm = TRUE))

## inspect the new variable
siteyear_summary


## make a table with new variable
siteyear_summary %>% 
  kable()
```


There are `r nrow(lobsters)` total lobsters included in this report.


```{r}
## Activity
siteyear_sum_med <- lobsters %>% 
  group_by(site, year) %>% 
  summarize(count_by_siteyear = n(),
            med_size_mm = median(size_mm, na.rm = TRUE),
            mean_size_mm = mean(size_mm, na.rm = TRUE),
            sd_size_mm = sd(size_mm, na.rm = TRUE))
gg_base <- ggplot(data = siteyear_sum_med,
      aes(x = year, y = mean_size_mm, fill = site))
  
l <- gg_base +
  geom_col() +
  theme_light() +
  labs(
    x = "site",
    y = "mean lobster size") +
  facet_wrap(~site)
l

ggsave(here("figures", "lobsters_col.jpg"), dpi = 180, width = 8, height = 7)
```

But we can redo all analyses with new data:

```{r}
## read in new data
lobsters <- read_xlsx(here("data/lobsters2.xlsx"), skip=4)

```

Using `count()`
```{r}
lobsters %>%
  count(site, year)

## This is the same as:
lobsters %>%
  group_by(site, year) %>% 
  summarize(n = n()) %>%
  ungroup()
```

```{r}
#use mutate() to add columns to dataframes

lobsters %>% 
  mutate(size_m = size_mm / 1000)

lobsters_detailed <- 
  lobsters %>% 
  mutate(size_m = size_mm / 1000, 
         millenia = 2000,
         observer = "Jewel Uzquiano")
```

```{r}
## use select() to choose columns to include
lobsters_detailed %>% 
  select(date, site, size_m)
```

